include 	  $(srctree)/arch/arm/mach-feroceon-kw/config/mvRules.mk
include 	  $(srctree)/arch/arm/mach-feroceon-mv78xx0/config/mvRules.mk
# This will never compile, because DUMMY will never by defined.
obj-$(DUMMY)   				:= dummy.o

