ifeq ($(CONFIG_ARCH_ARMADA370), y)
include $(srctree)/arch/arm/mach-armada370/config/mvRules.mk
endif
ifeq ($(CONFIG_ARCH_ARMADA_XP), y)
include $(srctree)/arch/arm/mach-armadaxp/config/mvRules.mk
endif
obj-$(CONFIG_BUFFALO_SATA_HOTPLUG_EVENT)	+= hdd_ctrl.o
