ifeq ($(CONFIG_ARCH_FEROCEON_ORION), y)
include $(srctree)/arch/arm/mach-feroceon-orion/config/mvRules.mk
endif
ifeq ($(CONFIG_ARCH_FEROCEON_KW), y)
include $(srctree)/arch/arm/mach-feroceon-kw/config/mvRules.mk
endif
ifeq ($(CONFIG_ARCH_FEROCEON_MV78XX0), y)
include $(srctree)/arch/arm/mach-feroceon-mv78xx0/config/mvRules.mk
endif
obj-$(CONFIG_BUFFALO_SATA_HOTPLUG_EVENT)	+= hdd_ctrl.o
