obj-$(CONFIG_BUFFALO_MATSU_PLATFORM)	+= hdd_ctrl.o
obj-$(CONFIG_BUFFALO_MATSU_PLATFORM)	+= btn_ctrl.o
obj-$(CONFIG_BUFFALO_MATSU_PLATFORM)	+= fan_ctrl.o
obj-$(CONFIG_BUFFALO_MATSU_PLATFORM)	+= cmos_ctrl.o
obj-$(CONFIG_BUFFALO_MATSU_PLATFORM)	+= boardid_ctrl.o
